name: Check Build

on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review
    paths-ignore:
    - '.github/**'
    - '.vscode/**'
    - '.gitignore'
    - '*.md'
    - 'CONTRIBUTORS/**'
    - 'docs/**'
    - 'examples/**'
    - 'imgs/**'
    - '.envrc'
  push:
    paths-ignore:
    - '.github/**'
    - '.vscode/**'
    - '.gitignore'
    - '*.md'
    - 'CONTRIBUTORS/**'
    - 'docs/**'
    - 'examples/**'
    - 'imgs/**'
    - '.envrc'

permissions:
  contents: read

jobs:
  build:
    name: Check if the project builds
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - uses: cachix/install-nix-action@v31

    - name: Enable flakes
      run: |
        mkdir -p ~/.config/nix
        echo "experimental-features = nix-command flakes" > ~/.config/nix/nix.conf

    - name: Setup Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@v14

    - name: Cache Cargo
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
        cache-provider: github
        cache-ttl: 14
        shared-key: "juno-rust-cache"
    - name: Check project
      run: |
        nix develop --command cargo check --locked --verbose

    - name: Build project
      run: |
        nix develop --command cargo build --locked --verbose
